# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auxilium' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auxilium
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'OneSignal'
  pod 'Alamofire', '~> 4.3'

  target 'AuxiliumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuxiliumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
